package com.zikool.edu.auth.bean;

public class TbRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_role.role_id
     *
     * @mbggenerated Sat Jun 15 15:44:47 CST 2013
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_role.role_name
     *
     * @mbggenerated Sat Jun 15 15:44:47 CST 2013
     */
    private String roleName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_role.role_id
     *
     * @return the value of tb_role.role_id
     *
     * @mbggenerated Sat Jun 15 15:44:47 CST 2013
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_role.role_id
     *
     * @param roleId the value for tb_role.role_id
     *
     * @mbggenerated Sat Jun 15 15:44:47 CST 2013
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_role.role_name
     *
     * @return the value of tb_role.role_name
     *
     * @mbggenerated Sat Jun 15 15:44:47 CST 2013
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_role.role_name
     *
     * @param roleName the value for tb_role.role_name
     *
     * @mbggenerated Sat Jun 15 15:44:47 CST 2013
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }
}