package com.zikool.edu.auth.bean;

public class TbRolePrivilege {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_role_privilege.id
     *
     * @mbggenerated Sat Jun 15 15:44:47 CST 2013
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_role_privilege.role_id
     *
     * @mbggenerated Sat Jun 15 15:44:47 CST 2013
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_role_privilege.privilege_id
     *
     * @mbggenerated Sat Jun 15 15:44:47 CST 2013
     */
    private Integer privilegeId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_role_privilege.id
     *
     * @return the value of tb_role_privilege.id
     *
     * @mbggenerated Sat Jun 15 15:44:47 CST 2013
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_role_privilege.id
     *
     * @param id the value for tb_role_privilege.id
     *
     * @mbggenerated Sat Jun 15 15:44:47 CST 2013
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_role_privilege.role_id
     *
     * @return the value of tb_role_privilege.role_id
     *
     * @mbggenerated Sat Jun 15 15:44:47 CST 2013
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_role_privilege.role_id
     *
     * @param roleId the value for tb_role_privilege.role_id
     *
     * @mbggenerated Sat Jun 15 15:44:47 CST 2013
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_role_privilege.privilege_id
     *
     * @return the value of tb_role_privilege.privilege_id
     *
     * @mbggenerated Sat Jun 15 15:44:47 CST 2013
     */
    public Integer getPrivilegeId() {
        return privilegeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_role_privilege.privilege_id
     *
     * @param privilegeId the value for tb_role_privilege.privilege_id
     *
     * @mbggenerated Sat Jun 15 15:44:47 CST 2013
     */
    public void setPrivilegeId(Integer privilegeId) {
        this.privilegeId = privilegeId;
    }
}