package com.zikool.edu.user.entity;

import java.io.Serializable;

public class User implements Serializable {

	private static final long serialVersionUID = 7671320503063991590L;

    private Integer userId;

    private String userName;

    private String userIdentityCard;

    private String userLoginName;

    private String roleName;

    private String userGender;

    private String userOrganization;

    private String userGrade;

    private String userProfessional;

    private String teachSubject;

    private String phone;

    private String email;

    private String qq;

    private String blog;

    private String address;

    private String password;

    private Integer organizationId;

    private Integer administratorId;

    private Integer roleId;
    
    private boolean delete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.user_id
     *
     * @return the value of tb_user.user_id
     *
     * @mbggenerated Mon Jun 24 16:52:09 CST 2013
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.user_id
     *
     * @param userId the value for tb_user.user_id
     *
     * @mbggenerated Mon Jun 24 16:52:09 CST 2013
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.user_name
     *
     * @return the value of tb_user.user_name
     *
     * @mbggenerated Mon Jun 24 16:52:09 CST 2013
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.user_name
     *
     * @param userName the value for tb_user.user_name
     *
     * @mbggenerated Mon Jun 24 16:52:09 CST 2013
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.user_identity_card
     *
     * @return the value of tb_user.user_identity_card
     *
     * @mbggenerated Mon Jun 24 16:52:09 CST 2013
     */
    public String getUserIdentityCard() {
        return userIdentityCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.user_identity_card
     *
     * @param userIdentityCard the value for tb_user.user_identity_card
     *
     * @mbggenerated Mon Jun 24 16:52:09 CST 2013
     */
    public void setUserIdentityCard(String userIdentityCard) {
        this.userIdentityCard = userIdentityCard == null ? null : userIdentityCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.user_login_name
     *
     * @return the value of tb_user.user_login_name
     *
     * @mbggenerated Mon Jun 24 16:52:09 CST 2013
     */
    public String getUserLoginName() {
        return userLoginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.user_login_name
     *
     * @param userLoginName the value for tb_user.user_login_name
     *
     * @mbggenerated Mon Jun 24 16:52:09 CST 2013
     */
    public void setUserLoginName(String userLoginName) {
        this.userLoginName = userLoginName == null ? null : userLoginName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.role_name
     *
     * @return the value of tb_user.role_name
     *
     * @mbggenerated Mon Jun 24 16:52:09 CST 2013
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.role_name
     *
     * @param roleName the value for tb_user.role_name
     *
     * @mbggenerated Mon Jun 24 16:52:09 CST 2013
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.user_gender
     *
     * @return the value of tb_user.user_gender
     *
     * @mbggenerated Mon Jun 24 16:52:09 CST 2013
     */
    public String getUserGender() {
        return userGender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.user_gender
     *
     * @param userGender the value for tb_user.user_gender
     *
     * @mbggenerated Mon Jun 24 16:52:09 CST 2013
     */
    public void setUserGender(String userGender) {
        this.userGender = userGender == null ? null : userGender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.user_organization
     *
     * @return the value of tb_user.user_organization
     *
     * @mbggenerated Mon Jun 24 16:52:09 CST 2013
     */
    public String getUserOrganization() {
        return userOrganization;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.user_organization
     *
     * @param userOrganization the value for tb_user.user_organization
     *
     * @mbggenerated Mon Jun 24 16:52:09 CST 2013
     */
    public void setUserOrganization(String userOrganization) {
        this.userOrganization = userOrganization == null ? null : userOrganization.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.user_grade
     *
     * @return the value of tb_user.user_grade
     *
     * @mbggenerated Mon Jun 24 16:52:09 CST 2013
     */
    public String getUserGrade() {
        return userGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.user_grade
     *
     * @param userGrade the value for tb_user.user_grade
     *
     * @mbggenerated Mon Jun 24 16:52:09 CST 2013
     */
    public void setUserGrade(String userGrade) {
        this.userGrade = userGrade == null ? null : userGrade.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.user_professional
     *
     * @return the value of tb_user.user_professional
     *
     * @mbggenerated Mon Jun 24 16:52:09 CST 2013
     */
    public String getUserProfessional() {
        return userProfessional;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.user_professional
     *
     * @param userProfessional the value for tb_user.user_professional
     *
     * @mbggenerated Mon Jun 24 16:52:09 CST 2013
     */
    public void setUserProfessional(String userProfessional) {
        this.userProfessional = userProfessional == null ? null : userProfessional.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.teach_subject
     *
     * @return the value of tb_user.teach_subject
     *
     * @mbggenerated Mon Jun 24 16:52:09 CST 2013
     */
    public String getTeachSubject() {
        return teachSubject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.teach_subject
     *
     * @param teachSubject the value for tb_user.teach_subject
     *
     * @mbggenerated Mon Jun 24 16:52:09 CST 2013
     */
    public void setTeachSubject(String teachSubject) {
        this.teachSubject = teachSubject == null ? null : teachSubject.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.phone
     *
     * @return the value of tb_user.phone
     *
     * @mbggenerated Mon Jun 24 16:52:09 CST 2013
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.phone
     *
     * @param phone the value for tb_user.phone
     *
     * @mbggenerated Mon Jun 24 16:52:09 CST 2013
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.email
     *
     * @return the value of tb_user.email
     *
     * @mbggenerated Mon Jun 24 16:52:09 CST 2013
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.email
     *
     * @param email the value for tb_user.email
     *
     * @mbggenerated Mon Jun 24 16:52:09 CST 2013
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.qq
     *
     * @return the value of tb_user.qq
     *
     * @mbggenerated Mon Jun 24 16:52:09 CST 2013
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.qq
     *
     * @param qq the value for tb_user.qq
     *
     * @mbggenerated Mon Jun 24 16:52:09 CST 2013
     */
    public void setQq(String qq) {
        this.qq = qq == null ? null : qq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.blog
     *
     * @return the value of tb_user.blog
     *
     * @mbggenerated Mon Jun 24 16:52:09 CST 2013
     */
    public String getBlog() {
        return blog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.blog
     *
     * @param blog the value for tb_user.blog
     *
     * @mbggenerated Mon Jun 24 16:52:09 CST 2013
     */
    public void setBlog(String blog) {
        this.blog = blog == null ? null : blog.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.address
     *
     * @return the value of tb_user.address
     *
     * @mbggenerated Mon Jun 24 16:52:09 CST 2013
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.address
     *
     * @param address the value for tb_user.address
     *
     * @mbggenerated Mon Jun 24 16:52:09 CST 2013
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.password
     *
     * @return the value of tb_user.password
     *
     * @mbggenerated Mon Jun 24 16:52:09 CST 2013
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.password
     *
     * @param password the value for tb_user.password
     *
     * @mbggenerated Mon Jun 24 16:52:09 CST 2013
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.organization_id
     *
     * @return the value of tb_user.organization_id
     *
     * @mbggenerated Mon Jun 24 16:52:09 CST 2013
     */
    public Integer getOrganizationId() {
        return organizationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.organization_id
     *
     * @param organizationId the value for tb_user.organization_id
     *
     * @mbggenerated Mon Jun 24 16:52:09 CST 2013
     */
    public void setOrganizationId(Integer organizationId) {
        this.organizationId = organizationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.administrator_id
     *
     * @return the value of tb_user.administrator_id
     *
     * @mbggenerated Mon Jun 24 16:52:09 CST 2013
     */
    public Integer getAdministratorId() {
        return administratorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.administrator_id
     *
     * @param administratorId the value for tb_user.administrator_id
     *
     * @mbggenerated Mon Jun 24 16:52:09 CST 2013
     */
    public void setAdministratorId(Integer administratorId) {
        this.administratorId = administratorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.role_id
     *
     * @return the value of tb_user.role_id
     *
     * @mbggenerated Mon Jun 24 16:52:09 CST 2013
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.role_id
     *
     * @param roleId the value for tb_user.role_id
     *
     * @mbggenerated Mon Jun 24 16:52:09 CST 2013
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

	public boolean isDelete() {
		return delete;
	}

	public void setDelete(boolean delete) {
		this.delete = delete;
	}
    
}